### ISSUE TITLE
Advanced adventuring, specifically structures

### ISSUE THREAD

**Issue by dealingwith** [dealingwith/MU#35]
### Overworld

- [x] Ruined nether portals @jamespeilunli 
- [x] Mineshaft @jamespeilunli 
- [x] Dungeons @dealingwith 
- [x] Desert pyramids @jamespeilunli 
- [x] Jungle temples @jamespeilunli 
- [x] Shipwrecks @dealingwith 
- [x] Buried treasure @jamespeilunli  
- [x] Ocean ruins (what are their real name?) @dealingwith 
- [x] Ocean monument (keep it simple) @dealingwith 
- [x] Igloos @jamespeilunli 
- [x] Pillager outpost @jamespeilunli
- [x] Woodland mansion @dealingwith 
- [x] Stronghold @dealingwith 

### Nether

- [x] Nether fortresses @dealingwith 
- [x] Bastion remnants @jamespeilunli 

Skip End structures for now.

**Comment by jamespeilunli** [comment]
[Wiki link](https://minecraft.fandom.com/wiki/Generated_structures)
